// Copyright © 2026 Mark Zaros. All Rights Reserved. License: GNU Public License 2.0 only.
enum WikipediaColorData {
    static let rows: [(hex: String, name: String)] = [
        ("#0048BA", "Absolute Zero"),
        ("#B0BF1A", "Acid Green"),
        ("#7CB9E8", "Aero"),
        ("#B284BE", "African Violet"),
        ("#72A0C1", "Air Superiority Blue"),
        ("#F0F8FF", "Alice Blue"),
        ("#DB2D43", "Alizarin"),
        ("#C46210", "Alloy Orange"),
        ("#EED9C4", "Almond"),
        ("#9F2B68", "Amaranth Deep Purple"),
        ("#F19CBB", "Amaranth Pink"),
        ("#AB274F", "Amaranth Purple"),
        ("#3B7A57", "Amazon"),
        ("#FFBF00", "Amber"),
        ("#9966CC", "Amethyst"),
        ("#3DDC84", "Android Green"),
        ("#C88A65", "Antique Brass"),
        ("#665D1E", "Antique Bronze"),
        ("#915C83", "Antique Fuchsia"),
        ("#841B2D", "Antique Ruby"),
        ("#FAEBD7", "Antique White"),
        ("#FBCEB1", "Apricot"),
        ("#00FFFF", "Aqua"),
        ("#7FFFD4", "Aquamarine"),
        ("#D0FF14", "Arctic Lime"),
        ("#4B6F44", "Artichoke Green"),
        ("#E9D66B", "Arylide Yellow"),
        ("#B2BEB5", "Ash Gray"),
        ("#FF9966", "Atomic Tangerine"),
        ("#FDEE00", "Aureolin"),
        ("#007FFF", "Azure"),
        ("#F0FFFF", "Azure (x11/web Color)"),
        ("#89CFF0", "Baby Blue"),
        ("#A1CAF1", "Baby Blue Eyes"),
        ("#F4C2C2", "Baby Pink"),
        ("#FEFEFA", "Baby Powder"),
        ("#FF91AF", "Baker-miller Pink"),
        ("#FAE7B5", "Banana Mania"),
        ("#DA1884", "Barbie Pink"),
        ("#7C0A02", "Barn Red"),
        ("#848482", "Battleship Grey"),
        ("#BCD4E6", "Beau Blue"),
        ("#9F8170", "Beaver"),
        ("#F5F5DC", "Beige"),
        ("#2E5894", "B'dazzled Blue"),
        ("#9C2542", "Big Dip O’ruby"),
        ("#FFE4C4", "Bisque"),
        ("#3D2B1F", "Bistre"),
        ("#967117", "Bistre Brown"),
        ("#CAE00D", "Bitter Lemon"),
        ("#000000", "Black"),
        ("#3D0C02", "Black Bean"),
        ("#54626F", "Black Coral"),
        ("#3B3C36", "Black Olive"),
        ("#BFAFB2", "Black Shadows"),
        ("#FFEBCD", "Blanched Almond"),
        ("#A57164", "Blast-off Bronze"),
        ("#318CE7", "Bleu De France"),
        ("#ACE5EE", "Blizzard Blue"),
        ("#660000", "Blood Red"),
        ("#0000FF", "Blue"),
        ("#1F75FE", "Blue (crayola)"),
        ("#0093AF", "Blue (munsell)"),
        ("#0087BD", "Blue (ncs)"),
        ("#0018A8", "Blue (pantone)"),
        ("#333399", "Blue (pigment)"),
        ("#A2A2D0", "Blue Bell"),
        ("#6699CC", "Blue-gray (crayola)"),
        ("#5DADEC", "Blue Jeans"),
        ("#126180", "Blue Sapphire"),
        ("#8A2BE2", "Blue-violet"),
        ("#5072A7", "Blue Yonder"),
        ("#3C69E7", "Bluetiful"),
        ("#DE5D83", "Blush"),
        ("#79443B", "Bole"),
        ("#E3DAC9", "Bone"),
        ("#CB4154", "Brick Red"),
        ("#D891EF", "Bright Lilac"),
        ("#FFAA1D", "Bright Yellow (crayola)"),
        ("#004225", "British Racing Green"),
        ("#CD7F32", "Bronze"),
        ("#964B00", "Brown"),
        ("#AF6E4D", "Brown Sugar"),
        ("#7BB661", "Bud Green"),
        ("#FFC680", "Buff"),
        ("#800020", "Burgundy"),
        ("#DEB887", "Burlywood"),
        ("#A17A74", "Burnished Brown"),
        ("#CC5500", "Burnt Orange"),
        ("#E97451", "Burnt Sienna"),
        ("#8A3324", "Burnt Umber"),
        ("#BD33A4", "Byzantine"),
        ("#702963", "Byzantium"),
        ("#5F9EA0", "Cadet Blue"),
        ("#91A3B0", "Cadet Grey"),
        ("#006B3C", "Cadmium Green"),
        ("#ED872D", "Cadmium Orange"),
        ("#A67B5B", "Café Au Lait"),
        ("#4B3621", "Café Noir"),
        ("#A3C1AD", "Cambridge Blue"),
        ("#C19A6B", "Camel"),
        ("#EFBBCC", "Cameo Pink"),
        ("#FFFF99", "Canary"),
        ("#FFEF00", "Canary Yellow"),
        ("#E4717A", "Candy Pink"),
        ("#C41E3A", "Cardinal"),
        ("#00CC99", "Caribbean Green"),
        ("#960018", "Carmine"),
        ("#D70040", "Carmine (m&p)"),
        ("#FFA6C9", "Carnation Pink"),
        ("#B31B1B", "Carnelian"),
        ("#56A0D3", "Carolina Blue"),
        ("#ED9121", "Carrot Orange"),
        ("#703642", "Catawba"),
        ("#C95A49", "Cedar Chest"),
        ("#ACE1AF", "Celadon"),
        ("#B2FFFF", "Celeste"),
        ("#DE3163", "Cerise"),
        ("#007BA7", "Cerulean"),
        ("#2A52BE", "Cerulean Blue"),
        ("#6D9BC3", "Cerulean Frost"),
        ("#1DACD6", "Cerulean (crayola)"),
        ("#0040FF", "Cerulean (rgb)"),
        ("#F7E7CE", "Champagne"),
        ("#F1DDCF", "Champagne Pink"),
        ("#36454F", "Charcoal"),
        ("#E68FAC", "Charm Pink"),
        ("#80FF00", "Chartreuse (web)"),
        ("#FFB7C5", "Cherry Blossom Pink"),
        ("#954535", "Chestnut"),
        ("#E23D28", "Chili Red"),
        ("#DE6FA1", "China Pink"),
        ("#AA381E", "Chinese Red"),
        ("#856088", "Chinese Violet"),
        ("#FFB200", "Chinese Yellow"),
        ("#7B3F00", "Chocolate (traditional)"),
        ("#D2691E", "Chocolate (web)"),
        ("#98817B", "Cinereous"),
        ("#E34234", "Cinnabar"),
        ("#CD607E", "Cinnamon Satin"),
        ("#E4D00A", "Citrine"),
        ("#9FA91F", "Citron"),
        ("#7F1734", "Claret"),
        ("#6F4E37", "Coffee"),
        ("#B9D9EB", "Columbia Blue"),
        ("#F88379", "Congo Pink"),
        ("#8C92AC", "Cool Grey"),
        ("#B87333", "Copper"),
        ("#DA8A67", "Copper (crayola)"),
        ("#AD6F69", "Copper Penny"),
        ("#CB6D51", "Copper Red"),
        ("#996666", "Copper Rose"),
        ("#FF3800", "Coquelicot"),
        ("#FF7F50", "Coral"),
        ("#893F45", "Cordovan"),
        ("#FBEC5D", "Corn"),
        ("#6495ED", "Cornflower Blue"),
        ("#FFF8DC", "Cornsilk"),
        ("#2E2D88", "Cosmic Cobalt"),
        ("#FFF8E7", "Cosmic Latte"),
        ("#81613C", "Coyote Brown"),
        ("#FFBCD9", "Cotton Candy"),
        ("#FFFDD0", "Cream"),
        ("#DC143C", "Crimson"),
        ("#9E1B32", "Crimson (UA)"),
        ("#F5F5F5", "Cultured Pearl"),
        ("#00B7EB", "Cyan (process)"),
        ("#58427C", "Cyber Grape"),
        ("#FFD300", "Cyber Yellow"),
        ("#F56FA1", "Cyclamen"),
        ("#FED85D", "Dandelion"),
        ("#654321", "Dark Brown"),
        ("#5D3954", "Dark Byzantium"),
        ("#008B8B", "Dark Cyan"),
        ("#536878", "Dark Electric Blue"),
        ("#B8860B", "Dark Goldenrod"),
        ("#006400", "Dark Green (x11)"),
        ("#1A2421", "Dark Jungle Green"),
        ("#BDB76B", "Dark Khaki"),
        ("#483C32", "Dark Lava"),
        ("#543D37", "Dark Liver (horses)"),
        ("#8B008B", "Dark Magenta"),
        ("#556B2F", "Dark Olive Green"),
        ("#FF8C00", "Dark Orange"),
        ("#9932CC", "Dark Orchid"),
        ("#301934", "Dark Purple"),
        ("#8B0000", "Dark Red"),
        ("#E9967A", "Dark Salmon"),
        ("#8FBC8F", "Dark Sea Green"),
        ("#3C1414", "Dark Sienna"),
        ("#8CBED6", "Dark Sky Blue"),
        ("#483D8B", "Dark Slate Blue"),
        ("#2F4F4F", "Dark Slate Gray"),
        ("#177245", "Dark Spring Green"),
        ("#00CED1", "Dark Turquoise"),
        ("#9400D3", "Dark Violet"),
        ("#555555", "Davy's Grey"),
        ("#DA3287", "Deep Cerise"),
        ("#FAD6A5", "Deep Champagne"),
        ("#B94E48", "Deep Chestnut"),
        ("#004B49", "Deep Jungle Green"),
        ("#FF1493", "Deep Pink"),
        ("#FF9933", "Deep Saffron"),
        ("#00BFFF", "Deep Sky Blue"),
        ("#4A646C", "Deep Space Sparkle"),
        ("#7E5E60", "Deep Taupe"),
        ("#1560BD", "Denim"),
        ("#2243B6", "Denim Blue"),
        ("#EDC9AF", "Desert Sand"),
        ("#696969", "Dim Gray"),
        ("#1E90FF", "Dodger Blue"),
        ("#4A412A", "Drab Dark Brown"),
        ("#00009C", "Duke Blue"),
        ("#EFDFBB", "Dutch White"),
        ("#555D50", "Ebony"),
        ("#C2B280", "Ecru"),
        ("#1B1B1B", "Eerie Black"),
        ("#614051", "Eggplant"),
        ("#F0EAD6", "Eggshell"),
        ("#CCFF00", "Electric Lime"),
        ("#BF00FF", "Electric Purple"),
        ("#8F00FF", "Electric Violet"),
        ("#50C878", "Emerald"),
        ("#6C3082", "Eminence"),
        ("#B48395", "English Lavender"),
        ("#AB4B52", "English Red"),
        ("#CC474B", "English Vermillion"),
        ("#563C5C", "English Violet"),
        ("#00FF40", "Erin"),
        ("#96C8A2", "Eton Blue"),
        ("#801818", "Falu Red"),
        ("#B53389", "Fandango"),
        ("#DE5285", "Fandango Pink"),
        ("#E5AA70", "Fawn"),
        ("#4F7942", "Fern Green"),
        ("#6C541E", "Field Drab"),
        ("#FF5470", "Fiery Rose"),
        ("#683068", "Finn"),
        ("#B22222", "Firebrick"),
        ("#CE2029", "Fire Engine Red"),
        ("#E25822", "Flame"),
        ("#EEDC82", "Flax"),
        ("#A2006D", "Flirt"),
        ("#FFFAF0", "Floral White"),
        ("#228B22", "Forest Green (web)"),
        ("#856D4D", "French Bistre"),
        ("#0072BB", "French Blue"),
        ("#FD3F92", "French Fuchsia"),
        ("#86608E", "French Lilac"),
        ("#9EFD38", "French Lime"),
        ("#D473D4", "French Mauve"),
        ("#FD6C9E", "French Pink"),
        ("#C72C48", "French Raspberry"),
        ("#77B5FE", "French Sky Blue"),
        ("#8806CE", "French Violet"),
        ("#E936A7", "Frostbite"),
        ("#FF00FF", "Fuchsia"),
        ("#C154C1", "Fuchsia (crayola)"),
        ("#E48400", "Fulvous"),
        ("#87421F", "Fuzzy Wuzzy"),
    ]
}